In [7]:
import torch
import torch.nn as nn
import torch.nn. functional as F
m1 = nn.Conv2d(16, 33, 3, stride=2)
# non-square kernels and unequal stride and with padding
m2 = nn.Conv2d(16,33, (3, 5), stride=(2, 1), padding=(4, 2))
# non-square kernels and unequal stride and with padding and dilation
m3= nn.Conv2d(16,33,(3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))

In [4]:
input = torch.randn(20, 16, 50, 100)
input

tensor([[[[ 1.7905e+00,  3.6153e-02,  3.6092e-01,  ..., -2.2447e+00,
            6.5660e-01,  4.5957e-01],
          [ 1.1256e+00,  2.5415e-01,  6.2063e-01,  ...,  8.8985e-02,
           -1.3597e+00, -2.4009e-01],
          [ 8.4884e-01,  2.0789e+00,  2.6082e-01,  ...,  5.4885e-01,
            3.5519e-02, -1.1104e-02],
          ...,
          [-7.7665e-01, -3.6054e-01, -1.3687e+00,  ..., -1.0861e+00,
           -1.0545e-01,  2.7338e-01],
          [-2.0630e-01,  3.2739e-01,  1.4177e+00,  ...,  7.7746e-01,
            6.1478e-01,  1.2348e+00],
          [ 5.0490e-01, -7.6588e-01,  1.7358e+00,  ..., -1.1372e+00,
            4.6409e-01,  2.1870e-01]],

         [[-2.3585e+00,  6.8922e-01,  2.8372e-01,  ...,  6.5391e-02,
           -6.7859e-02,  4.8888e-01],
          [-9.1142e-01,  1.3002e-01,  1.2840e+00,  ...,  3.6566e-01,
           -1.4484e+00, -1.2640e+00],
          [ 2.8497e-01,  1.0905e+00,  1.2630e-01,  ..., -1.8411e+00,
           -7.9772e-01, -1.4857e+00],
          ...,
     

In [14]:
output=m1(input)
output.shape

torch.Size([20, 33, 24, 49])

In [15]:
output=m2(input)
output.shape

torch.Size([20, 33, 28, 100])

In [16]:
output=m3(input)
output.shape

torch.Size([20, 33, 26, 100])

In [17]:
m = nn.ReLU()
input = torch.randn(5,5)
input

tensor([[ 0.4055, -0.5695,  0.1988,  1.7791,  0.1272],
        [-2.1327,  0.8557,  0.6125,  1.4465, -0.1212],
        [ 0.5089, -0.1756, -0.3013,  0.2216, -0.4554],
        [-1.1084, -1.1088,  1.3193,  0.1076, -1.8464],
        [ 0.2462,  1.4410,  0.8130,  0.0164, -0.2583]])

In [18]:
output=m(input)
output

tensor([[0.4055, 0.0000, 0.1988, 1.7791, 0.1272],
        [0.0000, 0.8557, 0.6125, 1.4465, 0.0000],
        [0.5089, 0.0000, 0.0000, 0.2216, 0.0000],
        [0.0000, 0.0000, 1.3193, 0.1076, 0.0000],
        [0.2462, 1.4410, 0.8130, 0.0164, 0.0000]])

In [19]:
m1 = nn.MaxPool2d(3, stride=2)
m2 = nn.MaxPool2d((3, 2), stride=(2,1))

In [20]:
input = torch.randn(2, 3, 4, 4)
input

tensor([[[[-1.1495, -0.7927,  0.4140, -1.5706],
          [ 1.3138,  1.1944,  0.9820, -0.6593],
          [-0.9568, -0.3523,  1.7604,  0.5511],
          [ 0.2743, -0.0485, -1.6023, -0.2180]],

         [[-0.4814,  1.3521, -0.3938, -1.1678],
          [-0.0569,  1.1275, -0.3408,  0.1426],
          [-1.2191, -1.4552, -0.2863,  0.9058],
          [ 1.3991,  1.0576,  0.8596, -0.7228]],

         [[ 1.0705,  0.6225, -0.8076, -1.4649],
          [ 0.9188, -0.9884,  0.2692, -0.0731],
          [ 0.2133, -1.6578,  0.2073, -0.3098],
          [-0.2076,  0.4556, -0.6311,  1.0403]]],


        [[[-0.3714,  1.1363, -0.2774,  0.8055],
          [-0.0886, -0.6261, -1.1786,  0.6326],
          [-1.1571,  0.8101,  0.9940, -0.3257],
          [ 1.5014, -1.4460, -2.7322,  0.8394]],

         [[-1.4722,  1.0154, -0.9062,  0.3634],
          [-0.8653, -1.7122,  1.7515, -0.7595],
          [ 0.8593,  1.9330,  1.0189, -2.2825],
          [-0.2540, -1.2714,  0.3270,  1.3718]],

         [[-1.1680,  0.7971,

In [21]:
output=m1(input)
output

tensor([[[[1.7604]],

         [[1.3521]],

         [[1.0705]]],


        [[[1.1363]],

         [[1.9330]],

         [[0.9321]]]])

In [22]:
output=m2(input)
output

tensor([[[[1.3138, 1.7604, 1.7604]],

         [[1.3521, 1.3521, 0.9058]],

         [[1.0705, 0.6225, 0.2692]]],


        [[[1.1363, 1.1363, 0.9940]],

         [[1.9330, 1.9330, 1.7515]],

         [[0.9321, 0.9321, 1.6642]]]])

In [23]:
input = torch.randn(2, 3, 4, 4)
input

tensor([[[[-0.4712,  0.0718, -0.5186, -2.4451],
          [ 0.7742,  0.4589,  0.2410,  1.8320],
          [ 2.3418,  1.2259,  0.1530, -0.3894],
          [ 0.7667, -0.4736,  1.2487,  1.6137]],

         [[ 0.1953, -0.1130, -0.5918,  1.1729],
          [-1.0304,  0.4293, -0.4477, -1.9704],
          [ 0.5635, -1.0643,  0.7377, -0.2790],
          [-1.1845,  0.1538, -1.6578,  0.1104]],

         [[ 0.2963, -0.7890, -0.4363,  0.1534],
          [ 0.1949, -1.7677,  0.8444, -1.4127],
          [ 0.6710, -0.4100,  1.1063,  0.8844],
          [ 1.0859,  1.0228, -0.4653, -0.1269]]],


        [[[-0.6839, -0.4115, -0.2413, -0.4559],
          [ 0.3204,  1.0430, -1.5794, -0.2884],
          [-0.3353, -0.9851,  0.9283,  0.3156],
          [ 0.5550, -0.2176,  0.0734,  2.0067]],

         [[ 0.1477, -1.1471,  0.4367, -1.4529],
          [-1.4437,  0.4707, -0.2958, -0.3795],
          [-2.3688,  0.9781, -0.9951, -0.5223],
          [ 1.8184, -1.6650, -2.3222,  0.8540]],

         [[ 0.0900, -0.2467,

In [26]:
m1 = nn.AvgPool2d(3, stride=2)
m2 = nn.AvgPool2d((3, 2), stride=(2,1))

In [27]:
output=m1(input)
output

tensor([[[[ 0.4752]],

         [[-0.1468]],

         [[-0.0322]]],


        [[[-0.2161]],

         [[-0.4686]],

         [[ 0.2027]]]])

In [28]:
output=m2(input)
output

tensor([[[[ 0.7336,  0.2720, -0.1878]],

         [[-0.1699, -0.1750, -0.2297]],

         [[-0.3007, -0.2421,  0.1899]]],


        [[[-0.1754, -0.2077, -0.2202]],

         [[-0.5605, -0.0921, -0.5348]],

         [[ 0.5135, -0.0773, -0.0877]]]])

In [29]:
m=nn.Linear(20,30)

In [30]:
input=torch.randn(2,20)
input

tensor([[-0.0883, -0.2115,  0.0515,  0.9393, -0.5870,  0.3676,  0.6928, -0.7086,
         -0.2827,  0.3685, -1.0519,  0.4421,  1.7489, -1.0337, -0.3272,  0.1280,
          0.4646,  0.5315, -0.3173,  0.2077],
        [ 0.7122, -0.6539, -0.6135,  0.0643,  1.9577, -0.2557,  0.7269,  2.4954,
          2.1799, -0.0358,  0.1262,  0.3253, -0.7327, -0.2171, -0.6977,  1.1629,
          0.1611, -0.2175, -1.2729, -1.1304]])

In [31]:
output=m(input)
output

tensor([[-0.3235,  0.5236,  0.1481, -0.4080,  0.0894, -0.6164, -1.0205, -0.2882,
          0.4729,  0.2347,  0.0573,  0.1823, -0.4085,  0.5767,  0.2730, -0.4553,
         -0.4828, -0.3370,  0.5898,  0.4098,  0.2438, -0.2171, -0.4090,  0.2199,
          0.1050, -0.2531,  0.0126,  0.3367, -0.5142,  0.0689],
        [-0.0062,  1.4566, -1.1989,  1.0524,  0.8619,  1.5315, -0.5964,  0.0739,
          0.3827,  0.0420,  0.6041, -0.3736,  0.5283, -0.7141, -0.8366,  0.9216,
          0.7708,  0.1454, -0.0976, -0.6898,  0.8652,  0.4183, -0.8034, -0.4081,
         -0.8927,  0.3770, -1.0907,  0.2422, -0.2947,  0.5603]],
       grad_fn=<AddmmBackward0>)